### ISSUE TITLE
rename master branch to devel

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/EuroBioC2023#4]
Hi organizers,

Perhaps Charlotte @csoneson or someone can change the default branch name to align with Bioconductor's code of conduct. 
See here for more information: http://contributions.bioconductor.org/branch-rename-faqs.html
I can also take care of this, if you'd like. 

Best regards,
Marcel

**Comment by csoneson** [comment]
Thanks @LiNk-NY - I don't think I have permissions to change the branch name, so if you could do that, it would be great.

**Comment by LiNk-NY** [comment]
Done! Thank you Charlotte!

**Comment by csoneson** [comment]
Thank you!
